import type { Metadata } from "next";
import {
  Oswald,
  Dancing_Script,
  Noto_Sans,
  Roboto,
  IBM_Plex_Mono,
  IBM_Plex_Sans,
  IBM_Plex_Sans_Condensed,
} from "next/font/google";
import "./globals.css";

const oswald = IBM_Plex_Sans_Condensed({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable}  antialiased`}
        style={{ fontFamily: "var(--font-oswald), Oswald, sans-serif" }}
      >
        {children}
      </body>
    </html>
  );
}
