version: "3.9"

services:
  main:
    build: . # path to your Next.js app (Dockerfile should be there)
    container_name: report-flow
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URI=mongodb://mongo:27017
      - NEXT_PUBLIC_URL=http://localhost:3000
      - PAYLOAD_SECRET="fjkdshi7h3iu"
    volumes:
      - app-data:/app/db/media 
    post_start:
      - command: bun run load
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    name: app_db
  app-data: 
    name: app_reports
